FROM node:18.16.1
WORKDIR /var/www/repo-backend-prod
COPY . .
RUN apt update && apt install awscli -y
RUN npm i
RUN npm install pm2 -g
EXPOSE 3002
RUN wget https://s3-prod-envs.s3.amazonaws.com/backend.env -O .env
RUN chmod 755 -R .
ENTRYPOINT ["./appstart.sh"]