FROM node:14.14.0 as build-stage

WORKDIR /var/www/repo-frontend-prod

COPY . .
RUN wget https://s3-prod-envs.s3.amazonaws.com/frontend.env -O .env
RUN npm install
RUN NODE_OPTIONS=--max_old_space_size=2048 npm run build

#production deploy part
FROM nginx:stable-alpine as deploy-stage
COPY default.conf /etc/nginx/conf.d
COPY --from=build-stage /var/www/repo-frontend-prod/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]